[project]
name = "signal-copier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kei Z3r0", email = "k3iz3r0@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
signal-copier = "signal_copier:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "hypothesis>=6.167.0",
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.5",
]

[tool.mypy]
explicit_package_bases = true
